---
- name: restart ethtool-gro
  ansible.builtin.systemd_service:
    name: ethtool-gro
    daemon_reload: false
    state: restarted

- name: reload strongswan
  ansible.builtin.command:
    cmd: swanctl --load-all
  changed_when: true

- name: restart strongswan
  ansible.builtin.systemd_service:
    name: strongswan.service
    state: restarted
