# yamllint disable rule:line-length
---
- name: create directory
  ansible.builtin.file:
    path: "{{ helm_item }}"
    owner: root
    group: root
    mode: !!str 0755
    state: directory
  loop:
    - /opt/helm
    - /opt/helm/{{ helm_version }}
  loop_control:
    loop_var: helm_item

- name: fetch checksum
  ansible.builtin.uri:
    url: https://get.helm.sh/helm-{{ helm_version }}-linux-amd64.tar.gz.sha256sum
    return_content: true
  register: helm_result
  until: helm_result is success

- name: set checksum fact
  ansible.builtin.set_fact:
    helm_checksum: "{{ helm_result.content | split('\n') | first | split(' ') | first }}"

- name: fetch tarball
  ansible.builtin.get_url:
    url: https://get.helm.sh/helm-{{ helm_version }}-linux-amd64.tar.gz
    checksum: sha256:{{ helm_checksum }}
    dest: /tmp/helm-{{ helm_version }}-linux-amd64.tar.gz
    owner: root
    group: root
    mode: !!str 0400
  register: helm_result
  until: helm_result is success

- name: unpack tarball
  ansible.builtin.unarchive:
    src: /tmp/helm-{{ helm_version }}-linux-amd64.tar.gz
    remote_src: true
    dest: /opt/helm/{{ helm_version }}
    owner: root
    group: root
    extra_opts:
      - --strip-components=1
    creates: /opt/helm/{{ helm_version }}/helm

- name: install binary
  ansible.builtin.file:
    path: /usr/local/bin/helm
    src: /opt/helm/{{ helm_version }}/helm
    owner: root
    group: root
    state: link
