---
ownca_client_names: "{{ vault_ownca_client_names }}"
ownca_common_name: "{{ vault_ownca_common_name }}"
ownca_country_name: "{{ vault_ownca_country_name }}"
ownca_mobileconfig: "{{ vault_ownca_mobileconfig }}"
ownca_root_privatekey_passphrase: "{{ vault_ownca_root_privatekey_passphrase }}"
