---
- name: publish application
  ansible.builtin.include_role:
    name: nginx
    tasks_from: site.yaml
  vars:
    nginx_server_name: "{{ library_application_name }}.{{ domain_name }}"
    nginx_src: media-proxy.conf.j2
    nginx_dest: media-proxy-{{ library_application_name }}
