# yamllint disable rule:line-length
---
- name: publish application
  ansible.builtin.include_role:
    name: nginx
    tasks_from: site.yaml
  vars:
    nginx_server_name: "{{ library_application_name }}.{{ domain_name }}"
    nginx_src: media-proxy.conf.j2
    nginx_dest: media-proxy-{{ library_application_name }}

- when: ansible_facts['system_vendor'] == 'Synology'
  block:
    - name: publish DNS
      delegate_to: tombstone
      ansible.builtin.import_role:
        name: unbound
        tasks_from: fragment.yml
      vars:
        unbound_content: |
          server:
            local-data: "{{ library_application_name }}.{{ domain_name }}. A {{ ansible_facts['default_ipv4'].address }}"
        unbound_dest: local-data-{{ library_application_name }}.conf

- when: ansible_facts['system_vendor'] != 'Synology'
  block:
    - name: publish DNS
      ansible.builtin.import_role:
        name: unbound
        tasks_from: fragment.yml
      vars:
        unbound_content: |
          server:
            local-data: "{{ library_application_name }}.{{ domain_name }}. CNAME {{ ansible_facts['hostname'] }}.{{ domain_name }}."
        unbound_dest: local-data-{{ library_application_name }}.conf
