---
ansible_become_flags: -s /bin/sh
ansible_become_method: su
k8s_kubeconfig: /etc/rancher/k3s/k3s.yaml
lego_path: /etc/lego
nginx_sites_enabled_path: /etc/nginx/sites-enabled
nologin_shell: /usr/sbin/nologin
