---
- name: install package
  ansible.builtin.apt:
    name: nftables
    state: present

- name: configure nftables
  ansible.builtin.template:
    src: nftables.conf.j2
    dest: /etc/nftables.conf
    owner: root
    group: root
    mode: !!str 0440
  notify: restart nftables

- name: enable and start service
  ansible.builtin.systemd_service:
    name: nftables.service
    enabled: true
    state: started

- name: flush handlers
  ansible.builtin.meta: flush_handlers
