$ANSIBLE_VAULT;1.1;AES256
65306235333563353235343065663063363862396637313732646634313565326631656531346266
6362343639646166323134666565373935616465343633350a626565613461326139363730333566
62386135353335646337393164633637646532326433343830393263363339363736666634616138
6165623762306233320a343830363838623931306432333163313232646330633633643266336665
3064
