# yamllint disable rule:line-length
---
# bazarr_config_addic7ed_cookies: "{{ vault_bazarr_config_addic7ed_cookies }}"
# bazarr_config_addic7ed_password: "{{ vault_bazarr_config_addic7ed_password }}"
# bazarr_config_addic7ed_user_agent: "{{ vault_bazarr_config_addic7ed_user_agent }}"
# bazarr_config_addic7ed_username: "{{ vault_bazarr_config_addic7ed_username }}"
# bazarr_config_addic7ed_vip: "{{ vault_bazarr_config_addic7ed_vip }}"
bazarr_config_auth_apikey: "{{ vault_bazarr_config_auth_apikey }}"
bazarr_config_general_enabled_providers: "{{ vault_bazarr_config_general_enabled_providers }}"
bazarr_config_general_flask_secret_key: "{{ vault_bazarr_config_general_flask_secret_key }}"
bazarr_config_opensubtitlescom_password: "{{ vault_bazarr_config_opensubtitlescom_password }}"
bazarr_config_opensubtitlescom_username: "{{ vault_bazarr_config_opensubtitlescom_username }}"
bitwarden_installation_id: "{{ vault_bitwarden_installation_id }}"
bitwarden_installation_key: "{{ vault_bitwarden_installation_key }}"
dns_updater_scw_access_key: "{{ vault_dns_updater_scw_access_key }}"
dns_updater_scw_secret_key: "{{ vault_dns_updater_scw_secret_key }}"
dns_updater_unifi_password: "{{ vault_dns_updater_unifi_password }}"
dns_updater_unifi_username: "{{ vault_dns_updater_unifi_username }}"
external_domain: "{{ vault_external_domain }}"
external_fqdn: "{{ vault_external_fqdn }}"
fluxcd_github_token: "{{ vault_fluxcd_github_token }}"
fluxcd_github_webhook_token: "{{ vault_fluxcd_github_webhook_token }}"
gateway: "{{ vault_gateway }}"
gitea_jwt_secret: "{{ vault_gitea_jwt_secret }}"
gitea_lfs_jwt_secret: "{{ vault_gitea_lfs_jwt_secret }}"
gitea_internal_token: "{{ vault_gitea_internal_token }}"
gitea_secret_key: "{{ vault_gitea_secret_key }}"
grafana_cloud_password: "{{ vault_grafana_cloud_password }}"
homebridge_config: "{{ vault_homebridge_config }}"
imapfilter_config: "{{ vault_imapfilter_config }}"
k0s_control_plane: true
lan_if: "{{ vault_lan_if }}"
lan_ipv4_address: "{{ vault_lan_ipv4_address }}"
lan_ipv6_address: "{{ vault_lan_ipv6_address }}"
lan_ipv6_link_address: "{{ vault_lan_ipv6_link_address }}"
lan_ipv6_link_subnet: "{{ vault_lan_ipv6_link_subnet }}"
lan_ipv6_subnet: "{{ vault_lan_ipv6_subnet }}"
lego_domains: "{{ vault_lego_domains }}"
lego_email: "{{ vault_lego_email }}"
lego_scaleway_api_token: "{{ vault_lego_scaleway_api_token }}"
library_path: /srv/media # FIXME: /srv/library
library_partition_uuid: "{{ vault_library_partition_uuid }}"
lidarr_api_key: "{{ vault_lidarr_api_key }}"
linkerd_identity_issuer_certificate: "{{ vault_linkerd_identity_issuer_certificate }}"
linkerd_identity_issuer_key: "{{ vault_linkerd_identity_issuer_key }}"
linkerd_identity_trust_anchors: "{{ vault_linkerd_identity_trust_anchors }}"
loki_push_url: "{{ vault_loki_push_url }}"
metallb_ip_address_pool: "{{ vault_metallb_ip_address_pool }}"
network_interfaces: "{{ vault_network_interfaces }}"
nzbget_add_password: "{{ vault_nzbget_add_password }}"
nzbget_add_username: "{{ vault_nzbget_add_username }}"
nzbget_control_password: "{{ vault_nzbget_control_password }}"
nzbget_control_username: "{{ vault_nzbget_control_username }}"
nzbget_news_servers: "{{ vault_nzbget_news_servers }}"
nzbget_restricted_password: "{{ vault_nzbget_restricted_password }}"
nzbget_restricted_username: "{{ vault_nzbget_restricted_username }}"
opensmtpd_aliases: "{{ vault_opensmtpd_aliases }}"
opensmtpd_relay_host: "{{ vault_opensmtpd_relay_host }}"
opensmtpd_secrets: "{{ vault_opensmtpd_secrets }}"
prometheus_pushover_token: "{{ vault_prometheus_pushover_token }}"
# prowlarr_api_key: "{{ vault_prowlarr_api_key }}"
qbittorrent_network_proxy_ip: "{{ vault_qbittorrent_network_proxy_ip }}"
qbittorrent_network_proxy_port: "{{ vault_qbittorrent_network_proxy_port }}"
qbittorrent_network_proxy_type: "{{ vault_qbittorrent_network_proxy_type }}"
radarr_api_key: "{{ vault_radarr_api_key }}"
# readarr_api_key: "{{ vault_readarr_api_key }}"
restic_b2_account_id: "{{ vault_restic_b2_account_id }}"
restic_b2_account_key: "{{ vault_restic_b2_account_key }}"
restic_password: "{{ vault_restic_password }}"
restic_repository: "{{ vault_restic_repository }}"
scw_organization_id: "{{ vault_scw_organization_id }}"
sonarr_api_key: "{{ vault_sonarr_api_key }}"
sops_age_key_file: "{{ vault_sops_age_key_file }}"
sshd_config_allow_users: "{{ vault_sshd_config_allow_users }}"
synology_csi_dsm_password: "{{ vault_synology_csi_dsm_password }}"
synology_csi_dsm_username: "{{ vault_synology_csi_dsm_username }}"
vault_synology_csi_dsm_username: k8scsi
tdarr_auth_secret_key: "{{ vault_tdarr_auth_secret_key }}"
tdarr_server: true
timemachine_partition_uuid: "{{ vault_timemachine_partition_uuid }}"
timemachine_valid_users: "{{ vault_timemachine_valid_users }}"
unbound_config_access_controls: "{{ vault_unbound_config_access_controls }}"
unbound_config_local_data: "{{ vault_unbound_config_local_data }}"
unbound_forwarders: "{{ vault_unbound_forwarders }}"
unbound_null_zones: "{{ vault_unbound_null_zones }}"
unbound_proxy_nl_zones: "{{ vault_unbound_proxy_nl_zones }}"
unbound_redirector_zones: "{{ vault_unbound_redirector_zones }}"
unbound_rpz_content: "{{ vault_unbound_rpz_content }}"
uptrace_dsn: "{{ vault_uptrace_dsn }}"
vaultwarden_admin_token: "{{ vault_vaultwarden_admin_token }}"
vaultwarden_smtp_password: "{{ vault_vaultwarden_smtp_password }}"
vaultwarden_smtp_username: "{{ vault_vaultwarden_smtp_username }}"
vpn_clients: "{{ vault_vpn_clients }}"
vpn_server_if: "{{ vault_vpn_server_if }}"
vpn_server_ipv4_address: "{{ vault_vpn_server_ipv4_address }}"
vpn_server_ipv6_address: "{{ vault_vpn_server_ipv6_address }}"
vpn_server_port: "{{ vault_vpn_server_port }}"
vpn_server_private_key: "{{ vault_vpn_server_private_key }}"
vpn_server_public_key: "{{ vault_vpn_server_public_key }}"
